services:
  - name: api-agencia
    type: web
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://<localhost>:<3309>/<db_travel>
      - key: SPRING_DATASOURCE_USERNAME
        value: <root>
      - key: SPRING_DATASOURCE_PASSWORD
        value: <root>
